### ISSUE TITLE
Child window?

### ISSUE THREAD

**Issue by drug007** [Devisualization/window#19]
Is it possible to create a child window using de_window? If not what prevents it?

**Comment by rikkimax** [comment]
Not currently.
It wasn't really why I originally made it.

I think we can agree that Devisualization.Window isn't really suitable for full blown GUI environments.
So, it's due for another round of work when the replacement of Devisualization.Image (I'm doing this on stream) is available.

In the mean time, can you add the new requirements to the wiki?
https://github.com/Devisualization/window/wiki

**Comment by drug007** [comment]
I see, thanks.
