### ISSUE TITLE
Can't build example

### ISSUE THREAD

**Issue by p0nce** [Devisualization/window#8]
Buiding the example program in test/

```
..\..\AppData\Roaming\dub\packages\de_image-0.3.1\source\mutable\devisualization
\image\mutable\manipulation.d(5): Error: module linegraph is in file 'devisualiz
ation\util\core\linegraph.d' which cannot be read
```

I think the problem is `de_image` relying on `de_util` v0.0.2 which is not the latest. Maybe `de_util` needs a new tag.

**Comment by rikkimax** [comment]
Just one question, are you using a custom build of dub?

**Comment by rikkimax** [comment]
I've updated all dependencies versions.
But I don't think this is what caused the issue.

**Comment by p0nce** [comment]
Erm, yes I am. I will update it to latest to see.

**Comment by rikkimax** [comment]
~master of dub currently adds source directory even if overridden.
Found that out thanks to @buggins

**Comment by p0nce** [comment]
Updated to latest DUB and now using de_window v0.0.7  and de_image v0.3.2.
I have the exact same error:
```
..\..\AppData\Roaming\dub\packages\de_image-0.3.2\source\mutable\devisualization
\image\mutable\manipulation.d(5): Error: module linegraph is in file 'devisualiz
ation\util\core\linegraph.d' which cannot be read
```

**To reproduce**: use `dub clean-caches` to  update the registry list cache, then use `dub` with this `dub.json` file:

```json
{
    "name": "test",
    "dependencies":
    {
        "de_window:platform": "==0.0.7"
    }
}
```

**Comment by rikkimax** [comment]
Wait, what version of dub are you using?
Also what is the output of dub build -v?

**Comment by p0nce** [comment]
I use DUB current master https://github.com/D-Programming-Language/dub/commit/de144e9c92e4ddda85b579ce12b9260b4cf7885f

dub -v => http://pastebin.com/icmrEgqk

**Comment by rikkimax** [comment]
What I was saying is dub master is broken.

```
import path[0] = ..\..\AppData\Roaming\dub\packages\de_image-0.3.2\source\interf
aces
import path[1] = ..\..\AppData\Roaming\dub\packages\de_image-0.3.2\source
import path[2] = c:\d\dmd.2.066.1\windows\bin\..\..\src\phobos
import path[3] = c:\d\dmd.2.066.1\windows\bin\..\..\src\druntime\import
```

It auto adds source directory during building even when sourcePaths is overridden. 
Basically if your subpackages are under source/ it will build them as well.
Which in this case is Devisualization.Image:mutable which is obviously not what you want.

https://github.com/D-Programming-Language/dub/issues/483

**Comment by p0nce** [comment]
I can confirm that DUB v0.9.22 does work. Since you have filed a DUB bug this can be closed.

**Comment by rikkimax** [comment]
I was unfortunately hoping this bug would go away without my help. Oh well.

**Comment by p0nce** [comment]
A work-around would be to supress the source/ directory level in de_image, like what is done in de_window.

**Comment by rikkimax** [comment]
I've thought about doing that. But only if dub itself will most likely be released like this. Until then I don't think its too much to ask to only support the released version.

**Comment by p0nce** [comment]
Absolutely.

**Comment by MartinNowak** [comment]
Fixed now
